### PR TITLE
Integration with Pulse Technology CRM

### PR DESCRIPTION
**Pull request by devguar**
Hello, I am Lucas Guarnieri from Pulse Technology team.
We have implemented needed functionalities to integrated WP-Fusion with our CRM, including the "search contact by tag" even being optional.

Any feedback is appreciated.

To know about Pulse, please look at the following link:
[Pulse Technology](https://thepulsespot.com/)

The integration is already tested in our local environment, if needed I can provide a online scenario to make the tests easier.

Thanks

### CODE REVIEW

**Comment by jack-arturo** [comment]
Hey @devguar , thanks for the PR! Looks pretty good. Can you share a PulseCRM login with us so that we can test the integration? You can email it to info@verygoodplugins.com

**Comment by devguar** [comment]
Hi @verygoodplugins , yes I can provide it, we actually had a small delay to release this integration at our side, it is only beta right now. Probably next week I'll be able to provide the credentials to an app to test.

**Comment by jack-arturo** [comment]
Ok no worries, we'll keep an eye out for your email :)

**Comment by devguar** [comment]
Hi @verygoodplugins , just sent you the email with the information you need to test. Let me know if you need something else.

**Comment by jack-arturo** [comment]
Hey @devguar ,

So we tried it out today but no tags or fields appeared in the dropdowns, and when we enabled HTTP API logging we got a 404 error trying to list custom fields. Seems like that URL is incorrect.

image

So it looks like it's not quite ready yet, could you fix those bugs?

As well, your code must follow the WordPress coding standards https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/

I'd suggest installing PHPCS with the WP coding standards package.

For example

* Method names are in camel case, they should be in snake case (strContains should be str_contains)
* Tabs should be used to indent, not spaces
* All functions should have docblock describing the parameters and return values

For additional information and examples see https://wpfusion.com/documentation/advanced-developer-tutorials/contributing-integration-modules/#contributing-to-wp-fusion

Thanks
Jack

**Comment by devguar** [comment]
Hi Jack, thanks for the update.
Sorry I think I gave you the incomplete information.

The URL that you should access to create your client app on Pulse is this one:
http://portal.feature-wpfusion-connection.dev.thepulsespot.com/ (with the credentials I sent you)

But the URL to use on WPFusion Setup page it actually this other:
http://app.feature-wpfusion-connection.dev.thepulsespot.com/

This is a bit weird on this testing scenario, but in a real situation it would be like (just a dumb example):
Our customer is called Lucas Shop, their system would be like: lucasshop.thepulsespot.com , but when you access this address without login in it will redirect you to portal.thepulsespot.com, there you can login. So we have a single portal that handle logins for all users on all companies, but each company have their own domain based app. So to create the app they will need to access the portal, but to use the system or the API the address is based on the business name.

Just updated now with the formatting fixes, I'm using phpStorm for it with the Wordpress code style defined, let me know if its correct now.

Can you check it again with this new address?

**Comment by jack-arturo** [comment]
Awesome, thanks. The code style and comments look great. We're able to connect and verify it's working as well. There are a few things we're going to smooth over with the initial setup, just so it doesn't take a save and refresh of the settings page...  but we'll take care of that.

We're going to aim to release this in next Monday's (July 7th) update unless there are any unexpected problems. Once we've released the integration in the full version we'll commit those changes back to your PR and accept it here as well.

Will keep you posted 👍😎

**Comment by devguar** [comment]
Hi @verygoodplugins , good to hear it, thanks for the heads up!

To double check, you said July 7th, you meaning June instead?
Just confirming to pass the info correctly to the people at my side.

Also, how can I add Pulse Technology CRM on the docs? It is on another repository?
https://wpfusion.com/documentation/#integrations

Thanks again!

**Comment by jack-arturo** [comment]
Accepted PR, thanks.

Yes, sorry, I meant Monday June 7th haha. So this coming Monday.

We'll get the docs updated on Monday as well when it goes out in the full version.

**Comment by jack-arturo** [comment]
Hey @devguar ,

That update went out in the full version of WP Fusion yesterday, and we've added PulseTechCRM to our compatibility table at https://wpfusion.com/documentation/faq/crm-compatibility-table/

The update will go out in the next version of WP Fusion Lite on wordpress.org (https://wordpress.org/plugins/wp-fusion-lite/) as well, I'm not sure exactly when.

Thanks again for your assistance.

**Comment by devguar** [comment]
Hi @verygoodplugins , thanks for releasing it.
I saw that you renamed **PulseTechnologyCRM** to **PulseTechCRM** , is there any specific reason for that?

Also, on the compatibility table is showing Pulse as not having webhooks, and we actually use webhooks when the contact is updated/created/tagged on Pulse we can run the webhooks to keep both updated... Its not enabled by default but its possible to configure. Can we change it?

**Comment by jack-arturo** [comment]
Hey @devguar ,

Ah, no, I just saw PulseTech in the code and thought that's what it was called. I've updated it on our site.

Yes, we can look at adding webhooks..... the login you sent to http://app.feature-wpfusion-connection.dev.thepulsespot.com/ stopped working yesterday, so we haven't been able to test anything. Can you set up a new login and send it to my email / show us where webhooks can be configured? Once we've had a chance to test it we'll put up a doc at https://wpfusion.com/documentation/#webhooks

**Comment by devguar** [comment]
Hi @verygoodplugins ,
Thanks for updating it.
We recorded a small video about how to configure webhooks on Pulse, since there are two different ways.

On the 00:50 on video the option 'Data to post' was changed to 'Merge fields' but the easiest way to use it is just leaving it as 'Contact entity', so it will post to the wordpress the contact that contains the ID required to make it work.

https://user-images.githubusercontent.com/6453377/121446189-5e8d4e00-c969-11eb-8b77-27b882d66918.mp4

The login you used is active now (same as sent via email).

**Comment by jack-arturo** [comment]
Thanks @devguar , we've confirmed it's working and updated the compatibility table. The new webhook docs are at https://wpfusion.com/documentation/webhooks/pulsetechnologycrm-webhooks/

**Pull request merged**
