### PR TITLE
Growmatik

### PR DESCRIPTION
**Pull request by hectorfarahani**
Hello, I am Hector Farahani from Artbees, Growmatik team.
Our CTO has contacted you about adding support for Growmatik as a CRM in WP Fusion.
We have implemented needed functionalities and left the "search contact by tag" as it seems optional.

Any feedback is appreciated.

To know about Growmatik, please look at the following links:
[Artbees](HTTP://artbees.net)
[Growmatik.ai](https://growmatik.ai/)
[Growmatik WordPress plugin](https://wordpress.org/plugins/marketing-automation-and-personalization/)
[Growmatik API Documentation](http://developers.growmatik.ai/)

You can contact me directly by hector@artbees.net 

Thanks

### CODE REVIEW

**Comment by jack-arturo** [comment]
Hey @hectorfarahani ,

Thanks. We've tried it out, but ran into a few issues.

Firstly, how exactly are contact custom fields managed in Growmatik? We've created custom fields but I can't see anywhere to edit the field values in the app.

Also in the code you've registered fields for firstName and lastName, but in Growmatik I can only see a Full Name field. Are firstName / lastName coming later?

Then there are three issues we'd need to get fixed before we can release it:

* Applying tags works, but removing tags does not. The API call to remove tags is giving a response "Please Provide email/tags fields". I tried adding an "email" parameter in the request body, but I'm still getting the error.
* Creating a new contact results in an error "The POST method is not supported for this route. Supported methods: GET, HEAD. (405 Method Not Allowed)"
* Updating an existing contact also throws the same error.

Otherwise everything looks fine. If you can get those three things fixed and update your PR we can include it in the next update.

**Comment by hectorfarahani** [comment]
Hi @verygoodplugins,

Thanks for your comment.

- Editing fields directly from the Growmatik panel is not possible for now. It is planned and it will be added soon.
- The Full Name is Generated automatically based on the First Name and Last Name.

The mentioned issues will be fixed and we will let you know about them. FYI, not any time sooner than the next Monday. 🎄

**Comment by hectorfarahani** [comment]
@verygoodplugins Hello, I have applied a bug fix, it was causing a problem in applying new tags from the user profile.

Also mentioned issues about API errors are fixed from the Growmatik side.

Please let us know if any further actions are needed from us.

**Comment by jack-arturo** [comment]
Awesome, thanks @hectorfarahani. This looks good.

We already released a beta integration with Growmatik in the full version of WP Fusion on Monday (v3.36): https://wpfusion.com/documentation/faq/changelog/.

We'll update that next week to fix the the bug with the tags overwriting the body.

And then this will go out in the next update of WP Fusion Lite as well, probably in March.

**Comment by hectorfarahani** [comment]
@verygoodplugins Thanks for informing us about updates.

I want to mention that we will provide another Pull Request to figure out some changes and possibly needed fixes on Monday.
It will be great if you consider the new PR for the next update.

**Comment by jack-arturo** [comment]
Yup that's fine. Thanks 🙂

**Pull request merged**
